### ISSUE TITLE
AttributeError:no 'clone'

### ISSUE THREAD

**Issue by aut6620** [KAIST-AILab/SMAAC#5]
Traceback (most recent call last):
  File "/home/lu/luohuan/SMAAC/SMAAC-master/test.py", line 174, in <module>
    trainer.train(
  File "/home/lu/luohuan/SMAAC/SMAAC-master/train.py", line 165, in train
    obs, reward, done, info = self.interaction(obs, prev_act, chronic_id, ffw, alive_frame)
  File "/home/lu/luohuan/SMAAC/SMAAC-master/train.py", line 71, in interaction
    action = self.agent.goal.clone()
AttributeError: 'NoneType' object has no attribute 'clone'
I don't know how it happen?
even thouth I delete the 'clone'
Traceback (most recent call last):
  File "/home/lu/luohuan/SMAAC/SMAAC-master/test.py", line 174, in <module>
    trainer.train(
  File "/home/lu/luohuan/SMAAC/SMAAC-master/train.py", line 165, in train
    obs, reward, done, info = self.interaction(obs, prev_act, chronic_id, ffw, alive_frame)
  File "/home/lu/luohuan/SMAAC/SMAAC-master/train.py", line 72, in interaction
    order = None if self.agent.order is None else self.agent.order.clone()
AttributeError: 'Agent' object has no attribute 'order'

**Comment by sunghoonhong** [comment]
I've never seen this kind of error before. 
I'd like to know if you modify source code or use packages with different version, especially, pytorch or grid2op.
Could you add more detailed explanation?

**Comment by aut6620** [comment]
The issue has been solved! Thanks for your reply!
